sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
  - "6.11.0"

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_install:
  - # start your web application and listen on `localhost`
  - # google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --dump-dom http://localhost:8100 &
  - npm install

before_script:
  - wget -N http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  # - node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.29
  # - node_modules/protractor/bin/webdriver-manager start --versions.chrome 2.29 2>&1 &
  - sleep 5

script:
  - npm run unit-test
  - npm run functional-test
