language: node_js
node_js:
  - "node"
  - "6.11.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
      - libgnome-keyring-dev

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - npm run unit-test
  - npm run functional-test
