dist: trusty
language: node_js
node_js:
  - "node"
  - "6.11.0"

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
      - libgnome-keyring-dev

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8100 &
  - npm install

before_script:
  - node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.29
  - node_modules/protractor/bin/webdriver-manager start 2>&1 &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - npm run unit-test
  - npm run functional-test
