sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 7

env:
  global:
    - API_KEY=AIzaSyDNGPh2ERYJq9Ei1tzDSNG-nOyYAJVhpY4
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - node ./node_modules/protractor/bin/webdriver-manager update
script:
  - npm run ci
